server:
  port: 8070
  jpa:
    show-sql: true
logging.level.com.zjnu.mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: liguanghuijia1
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  pool:
    max-active: 8 #最大连接数
    max-idle: 8 #最大空闲连接
    min-idle: 0 #最小空闲连接
    max-wait: 1000 #连接等待时间，ms

mybatis:
  mapper-locations:
    classpath: mapper/*Mapper.xml
    type-aliases-package: com.zjnu.mapper
